### ISSUE TITLE
(Instructor) Starter Code Setup

### ISSUE THREAD

**Issue by pconrad** [project-anacapa/course-github-org-tool#6]
As an instructor, I can set up starter code for an assignment SO THAT we can offer a tool that creates repos with the correct naming convention and starter code.

The starter repo convention is a (either private or public) repo called  STARTER_ssss  where sss is a string of any length, and is the assignment name.   

private or public?

* It's private to avoid students "forking" it instead of following our preferred workflow.

**Comment by ncbrown1** [comment]
Note: This will be a setting in the assignment_spec.json. If unspecified, there will be no starter code for the assignment, and students will start off with an empty repository when they checkout the assignment. If specified, the value will be a URL (or just the repo name) to the starter code for the assignment.
