### ISSUE TITLE
(Student) Starter Code Checkout

### ISSUE THREAD

**Issue by pconrad** [project-anacapa/course-github-org-tool#7]
As a student, I can create a repo for an assignment (initially single only, pair separate story)
so that I can work on the assignment in a private repo that has the right permission, and the right starter code, and all the right settings, etc. and naming conventions.

Having option of a pair partner is a separate story.

**Comment by ncbrown1** [comment]
Note: From issue #13, we can see the list of all repos. Corollary from that is that we can see the list of all assignments for the course!

Implementation: Select an assignment, and click some sort of "checkout" button that creates the repo for them.
